- frontend/packages/dev-console/src/components/pipelineruns/logs/MultiStreamLogs.tsx
<Logs> component 가 나오지 않고 있는 문제
containers 갯수가 0 이상일때만 logs 나오게 변경하고, container 가 없을시 문구 추가
> [feat][patch][IMS]290757 파이프라인 수행 후 로그 조회 시 문구 추가 개선 요청

- frontend/packages/dev-console/src/components/pipelines/pipeline-builder/task-sidebar/temp-utils.tsx
[feat][patch] 파이프라인 생성페이지 사이드바 파라미터 값 부분 TextArea로 수정 및 autoscale 적용
파이프라인 생성페이지 사이드바 파라미터 값 부분 TextArea로 수정 및 text에 따른 높이 값 변경 적용
> [feat][patch] 파이프라인 생성페이지 사이드바 파라미터 값 부분 TextArea로 수정 및 autoscale 적용

- frontend/public/components/factory/list-page.jsx
- frontend/public/components/utils/firehose.jsx
- frontend/public/components/utils/status-box.tsx
> [feat][patch] CRD 없는 경우에 대한 에러페이지 수정 및 앱 초기 로딩 시 에러 화면이 표시되는 현상 수정

- frontend/public/components/factory/list-page.jsx
- frontend/public/components/hypercloud/crd/create-pinned-resource.tsx
생성 폼 helpText 한영 변환되지 않는 현상 수정  
비 k8s 리소스인 경우 crd 에러 화면 나오는 현상 수정
> [bugfix] 생성 폼 helpText 한영 변환되지 않는 현상 수정 & 비 k8s 리소스인 경우 crd 에러 화면 나오는 현상 수정 & 리스트 페이지 하단 로딩창 수정

- frontend/public/components/hypercloud/redis-cluster.tsx
- frontend/public/components/hypercloud/redis.tsx
레디스, 레디스 클러스터 상세페이지의 grafana url을 마스터 클러스터 -> 홈 -> 그라파나 메뉴에서 사용하는 url로 수정.
IMS: 290689
> [bugfix][patch] 레디스, 레디스 클러스터 상세페이지 grafana url 수정

- frontend/public/components/hypercloud/form/clustertasks/step-modal.tsx
- frontend/public/components/hypercloud/form/tasks/step-modal.tsx
> [bugfix][patch] 태스크/클러스터태스크 스탭 모달의 환경변수 필드 삭제시 타입 값 누락되는 현상 수정

- frontend/public/components/hypercloud/form/index.ts
- frontend/public/components/hypercloud/form/pipelineresources/create-pipelineresource.tsx
- frontend/public/components/hypercloud/form/pipelineresources/sync-form-data.ts
> [feat][patch] 파이프라인 리소스 폼, YAML 뷰 연동 기능 추가

- frontend/public/components/edit-yaml.jsx
- frontend/public/components/hypercloud/crd/create-pinned-resource.tsx
- frontend/public/components/hypercloud/crd/edit-resource.tsx
- frontend/public/components/hypercloud/form/index.ts
- frontend/public/components/utils/horizontal-nav.tsx
github 에서 바로 schema 받는 방식 PR 입니다.
다만 이게 맞는지는 다시 검토가 필요하지 않을까 싶습니다.
(외부 접속 하는게 맞는지 등)
> github 에서 바로 schema 받는 방식

- docs/page-clustermenupolicy/index.md
CMP 사용 가이드 kind에 레디스, 레디스 클러스터 추가
> [feat][patch] CMP 사용 가이드 kind에 레디스, 레디스 클러스터 추가

- frontend/public/components/hypercloud/redis-cluster.tsx
- frontend/public/components/hypercloud/redis.tsx
[patch][bugfix] grafana url text 변수화 적용
IMS: 290689
> [patch][bugfix] grafana url text 변경

- frontend/public/components/filter-toolbar.tsx
[feat][patch][IMS]290756 filter 한번에 다중 선택 가능]
filter 선택 변경시 자동 close 되지 않도록 수정
[bugfix][IMS]290756 filter 한번에 다중 선택 가능 - checkbox bug 수정
isChecked = true 이면 dropDownItems 내부의 CheckBox component 에서 <input ... checked> 상태로 생성되고 변경사항이 적용되지 않는 문제 발생
checked 로 변경 후 정상동작 확인
> 290756 filter 한번에 다중 선택 가능

- frontend/public/components/hypercloud/form/servicebindings/backup-service-item.tsx
- frontend/public/components/hypercloud/form/servicebindings/bindable-resource-list-drop-down.tsx
- frontend/public/components/hypercloud/form/servicebindings/create-servicebinding.tsx
- frontend/public/components/hypercloud/utils/resource-list-dropdown.tsx
서비스바인딩 리소스 선택 / 직접 입력 연동 기능 추가
* 애플리케이션
* 백업서비스
> [feat][patch] 서비스바인딩 리소스 선택 / 직접 입력 연동 기능 추가

- frontend/packages/dev-console/src/components/pipelines/pipeline-builder/PipelineBuilderEditPage.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-builder/PipelineBuilderForm.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-builder/PipelineBuilderPage.tsx
- frontend/packages/dev-console/src/components/pipelines/pipeline-builder/types.ts
- frontend/packages/dev-console/src/components/pipelines/pipeline-builder/utils.ts
- frontend/public/components/hypercloud/form/index.ts
- frontend/public/components/hypercloud/pipeline.tsx
[feat][patch] 파이프라인 폼, YAML 뷰 연동 기능 추가
> [feat][patch] 파이프라인 폼, YAML 뷰 연동 기능 추가

- frontend/public/components/hypercloud/redis-cluster.tsx
레디스 클러스터 개요 페이지의 컨피그 맵에 리소스 링크 추가
IMS: 293327
> [feat][patch] 레디스 클러스터 개요 페이지의 컨피그 맵에 리소스 링크 추가

- frontend/packages/dev-console/src/components/topology/components/nodeContextMenu.tsx
- frontend/packages/dev-console/src/plugin.tsx
[feat][patch][IMS]293311 토폴로지 메뉴 기능 이슈 - 카탈로그 메뉴 유형 체크 적용
herf 에 Cluster Service Class, Service Class 추가
[feat][patch][IMS]293311 토폴로지 메뉴 기능 이슈 - 우클릭 메뉴 막음
graphContextMenu 빈 배열로 변경함
> IMS 293311 토폴로지 메뉴 기능 이슈

- frontend/public/actions/dashboards.ts
- frontend/public/components/dashboard/with-dashboard-resources.tsx
마스터클러스터, 싱글클러스터 개요 페이지 대시보드 데이터 남아있는 문제 수정.
화면 전환시 이전 dashboard 데이터를 초기화하여 로딩화면으로 대체.
IMS: 292731
> [bugfix][patch] 마스터클러스터, 싱글클러스터 개요 페이지 대시보드 토큰 남아있는 문제 수정

- docs/index.markdown
- frontend/public/components/hypercloud/kafkarebalance.tsx
레이블을 지정된 형식(strimzi.io/cluster)과 다르게 넣거나 아예 입력하지 않은 경우에도 화면을 뜨되 해당 항목이 비어있도록 수정
list
detail
> [feat][patch] IMS 293381 레이블에 따른 예외처리

- frontend/public/components/error.tsx
ingress 에러 페이지 문구 수정
ErrorComponent 에 link, linkText 추가
> [feat][patch][IMS]288690 helm-apiserver 없을 시 개발자 - 헬름 메뉴 오류 문구 기획 요청

- frontend/public/components/hypercloud/modals/invite-member-modal.tsx
> [feat][patch][IMS 294385] 클러스터 초대 group 초대 기능 UI 제거 요청

- frontend/public/components/dashboard/dashboards-page/cluster-dashboard/queries.ts
- frontend/public/components/hypercloud/form/index.ts
- scripts/run-console.sh
싱글클러스터 콘솔 잔여 이슈 진행
1. 홈 > 네임스페이스
네임스페이스 개요에서 네트워크 전송 쿼리 수정 반영
2. 홈 > 네임스페이스
네임스페이스 상세에서 클레임 판넬 이슈
클러스터 템플릿 클레임, 롤바인딩 클레임 링크 각각 클릭시 "404 Not Found" 발생 수정
- 해당 사항은 다음 회의 이후에 정해진다고 합니다.
3. 홈 > 네임스페이스
네임스페이스 상세에서 미터링 탭 화면 이슈
해당 이슈는 다른 이슈로 분리되었습니다.
4. 관리 > 사용자 리소스 정의
"관리 > 사용자 리소스 정의" 화면에서 특정 CRD를 선택한 후 "인스턴스 > [특정 CRD] 생성"을 누르면 아래와 같이 페이지가 정상적으로 뜨지 않습니다.
아래와 같이 api콜 요청 경로가 올바르지 않은 듯 보여집니다.
url 부분이 잘못되어져있어 수정하였습니다.
(현재 [특정 CRD] 생성" 누를시)
> [feat][patch][IMS 294550] 싱글클러스터 콘솔 잔여 이슈 수정

- frontend/public/components/hpa.tsx
> [feat][patch][IMS 294302] HPA메트릭 수치 표시가 안되는 문제 수정

- frontend/public/components/events.jsx
- frontend/public/components/service.jsx
event page 기간내 이벤트 조회 기능 제거
service page trace tab 제거
> [feat][patch][IMS 294550] 싱글클러스터 콘솔 잔여 이슈 수정 - event page, service page

- frontend/packages/console-app/src/components/nodes/NodeDetailsPage.tsx
- frontend/public/hypercloud/auth.js
싱글 클러스터 호스트 노드 상세페이지 Toast popup 추가
기획
구현
> [feat][patch][IMS 294447] 클러스터클레임 생성시 싱글클러스터 모니터링 조회 이슈 관련하여 문구 추가 요청

- frontend/packages/console-app/src/components/nodes/NodeDetailsPage.tsx
- frontend/packages/console-app/src/components/nodes/node-dashboard/NodeDashboard.tsx
- frontend/public/components/pod.tsx
- frontend/public/hypercloud/auth.js
node page 내 alert 위치 변경
pod page alert 추가
alert style 추가
(component 화 및 css 작성 등 추후 작업 필요해 보임)
(디자인 문서는 다음주에 나올예정)
> [feat][patch][IMS 294447] 클러스터클레임 생성시 싱글클러스터 모니터링 조회 이슈 관련하여 문구 추가 요청 - pod page 추가

- frontend/public/components/pod.tsx
> [feat][patch][IMS 294447] 스트링 수정에 맞게 코드 수정

- frontend/public/components/utils/link.tsx
what: 하이퍼 클라우드 메뉴얼 링크를 변경하였습니다.
why: ims 요청이 올라왔습니다.
how: 링크 부분을 직접 수정하였습니다.
> [feat][patch][IMS 295098] 메뉴얼 링크 수정

- frontend/packages/console-app/src/components/nodes/node-dashboard/NodeDashboard.tsx
- frontend/public/components/pod.tsx
- frontend/public/components/utils/hypercloud/_toast-popup-alert.scss
- frontend/public/components/utils/hypercloud/toast-popup-alert.tsx
- frontend/public/hypercloud/auth.js
- frontend/public/style.scss
ToastPopupAlert Component 추가
ToastPopupAlert 디자인 기획 업데이트 되어서  padding  추가 작업 및 component로 따로 분리
기획
구현
> [refact]ToastPopupAlert Component 추가

- frontend/packages/dev-console/src/utils/pipeline-augment.ts
- frontend/public/components/hypercloud/pipeline-run.tsx
- frontend/public/components/hypercloud/task-run.tsx
> [IMS 291978] 파이프라인 런, 테스크 런 상세화면에 secret 필드 추가

- frontend/public/components/hypercloud/create-sample.tsx
- frontend/public/components/utils/hypercloud/toast-popup-alert.tsx
- frontend/public/hypercloud/auth.js
Add toast-popup-alert in create-sample.tsx
> [chore] Add toast-popup-alert in create-sample.tsx

- frontend/packages/dev-console/src/components/pipelineruns/logs/MultiStreamLogs.tsx
문구 추가
string 에러 로 인해 ko.json, en.json 수정
해당 사항 구광모 연구원과 공유함
> [feat][patch][IMS 290757] [5.0] [천주교] 파이프라인 수행 후 job pod 삭제 및 로그 조회 시 문구 추가

- frontend/public/components/factory/list-page.jsx
what: 해당 페이지가 메뉴에 없고, crd에 존재하지 않는 경우 생성버튼을 누를시에 import page로 이동하도록 수정했습니다.
Why: 이전 cis driver 나 endpoint, api서비스 같은 리소스에 생성 버튼을 누르면 무한 로딩 되는 경우를 확인했습니다
how: isCustomResourceType 를 통해서 따로 생성한 메뉴가 있는지 먼저확인을 한다음 CRD 목록을 확인한뒤 해당 리소스가 존재하지 않는경우 import 페이지와 연결했습니다.
> [feat] 해당 페이지가 메뉴에 없고, crd에 존재하지 않는 경우 생성버튼을 누를시에 import page로 이동하도록 수정

- frontend/public/hypercloud/menu/hc-default-menus.ts
what:ai devpos 대 메뉴에서 보이지 않도록 수정하였습니다.
why: ai본부에서 업무 가져가는 방향 논의중 이며, 결정되는대로 정완팀장님이 전달해 주시기로 하였습니다.
그전까지는 일단 대메뉴 안보이게 처리 해야한다고 합니다.
https://www.notion.so/0b4ea19b3efd4c0ca17b9162a84cc4f8?v=45f05f796309453dba0237bc41d10ba4
how: 해당페이지가 보이지 않도록 주석처리 하였습니다.
> ai devpos 대 메뉴에서 보이지 않도록 수정

- frontend/public/actions/k8s.ts
- frontend/public/components/app-contents.tsx
- frontend/public/components/error.tsx
what: api 서비스에서 정보를 가져오는 부분에서 오류가 나면 해당페이지로 이동되도록 수정하였습니다.
> [feat][patch] api 서비스 유효하지 않을시 해당 오류 페이지 렌더링

- frontend/public/components/app-contents.tsx
주성으로 되어있던 
webpackChunkName 수정완료했습니다.
> [feat][patch] api 서비스 유효하지 않을시 해당 오류 페이지 렌더링(webpackChunkName 수정)

- frontend/packages/console-app/src/components/nodes/node-dashboard/NodeDashboard.tsx
"클러스터 클레임을 통해 aws 프로바이더 싱글 클러스터를 생성한 경우" 만 alert 나오게 해야한다는 기획자료 확인
(현재는 싱글클러스터이면 무조건 나오고 있음)
(Unknown 일때 동작은 추가로 기획 확인 중)
> [bugfix] node 개요페이지 provider 가 aws 일때만 ToastPopup 생성

- frontend/public/module/k8s/get-resources.ts
what: 디플로이먼트 리소스 아이콘 DEP로 뜨는부분 D로 수정하였습니다.
why: 사진 처럼 포폴로지 화면에서만 3글자로 나타나던 DEP글자를 D로 바꾸었습니다.
> [feat][patch] 디플로이먼트 리소스 아이콘 DEP로 뜨는부분 D로 수정

- frontend/public/components/hypercloud/virtual-service.tsx
네임스페이스가 Status 로 되어 있는것을 발견하여 수정
> [bugfix] namespace 리소스 링크 수정

- frontend/public/components/hypercloud/role-binding-claim.tsx
what:롤 바인딩 클레임 사용자 이름 컬럼을 구현 하였습니다.
> [feat][patch] 롤 바인딩 클레임 사용자 이름 컬럼 구현

- frontend/public/components/hypercloud/cluster.tsx
[기능]
- cluster 상세페이지의 타입값과 리스트페이지의 타입값이 다른 현상 수정
- 클러스터 수정 액션 버튼 제거 
- group 데이터 대신 member 데이터 보여주고 있던 부분 수정 
[lint 에러]
- Unexpected console statement no-console 수정
- Do not pass children as props. Instead, nest children between the opening and closing tags 수정
> [bugfix][patch]cluster > 클러스터 수정 action제거 및 list와 detail페이지에서 type값 다른현상 수정

- frontend/public/components/hypercloud/pipeline-run.tsx
- frontend/public/components/hypercloud/task-run.tsx
> [bugfix][patch] ims291978 테스크런, 파이프라인런에서 시크릿값 안보이는 이슈 수정

- frontend/public/components/catalog/catalog-item-details.jsx
- scripts/run-console.sh
이전에 이상한 주소로 라우팅이 되어있던 서비스 인스턴스 카탈로그 가이드 라우팅을 수정하였습니다.
> [feat][patch]서비스 인스턴스 카탈로그 가이드 수정

- frontend/public/components/hypercloud/cluster-claim.tsx
cluster 필터링 기준이 실제 클레임 상태와 다른 상태를 수정하였습니다.
기존의 상태에 맞추어 필터를 수정하였습니다.
> [feat][patch] cluster 필터링 기준이 실제 클레임 상태와 다름 수정

- frontend/public/components/hypercloud/kafkamirrormaker2.tsx
- Expandable Table적용 
- 미러수 컬럼 참조값 변경
> [feat][patch][IMS 296608] 카프카 미러메이커 2 리스트화면 기획반영

- frontend/packages/console-shared/src/utils/resource-utils.ts
- frontend/packages/dev-console/src/components/topology/components/componentFactory.ts
- frontend/packages/dev-console/src/components/topology/components/const.ts
- frontend/packages/dev-console/src/components/topology/components/hypercloud/nodes/PVCNode.tsx
- frontend/packages/dev-console/src/components/topology/data-transforms/data-transformer.ts
- frontend/packages/dev-console/src/components/topology/data-transforms/hypercloud/transform-utils.ts
- frontend/packages/dev-console/src/components/topology/layouts/hypercloud/layoutConstraints.ts
[전]
[후]
- pvc node 가공을 위한 로직추가 
- status 데코레이터를 위한 로직추가 
- 관련 파일들 린트 에러 나는 부분들 수정
> [feat][patch] Topology > pvc 노드 icon 변경 및 status 데코레이터 추가

- frontend/public/components/hypercloud/form/pipelineruns/sync-form-data.ts
what: 테스크런 생성페이지 리팩토링을 진행했습니다.
how: 1차적으로 연쇄 조건무을 스위치 문으로 변경했습니다.
> [feat][patch] 테스크런 생성페이지 리팩토링

- frontend/packages/console-shared/src/utils/resource-utils.ts
- frontend/packages/dev-console/src/components/topology/data-transforms/data-transformer.ts
전달 인수 문제로 테스트 코드와 부분 코드에서 생기는 문제해결하였습니다
(전)
(후)
> [feat][patch] 전달 인수 문제로 테스트 코드에서 생기는 문제해결

- frontend/public/components/hypercloud/trained-model.tsx
- frontend/public/models/hypercloud/index.ts
ai-devops 모듈 버전 업그레이드를 진행으로 인한 console로직 변경 하였습니다. 
api 그룹 변경과 실환경 crd 추가, 없을 가능성 있는 요소 옵셔널 체이닝을 하였습니다.
cc
> [feat][patch][IMS 298069] ai-devops 모듈 버전 업그레이드를 진행으로 인한 console로직 변경

- frontend/.eslintrc
- frontend/public/components/hypercloud/service-instance.tsx
- scripts/run-console.sh
- service instance > detail의 yaml 페이지 수정가능 하도록 수정 
- eslint 에러 수정
> [patch][IMS 290804] service instance 수정가능하도록 변경

- frontend/packages/dev-console/src/utils/hc-status-reducers.ts
- frontend/public/components/hypercloud/kafkarebalance.tsx
- detail화면의 heading status icon추가 작업 진행
- KafkaRebalanceReducer 추가
- hc-status-reduces.ts 린트 에러 수정
> [feat][patch] detail화면의 heading status icon추가 작업

- frontend/.eslintrc
- frontend/public/components/hypercloud/kafkamirrormaker2.tsx
- frontend/public/components/hypercloud/tags.tsx
- frontend/public/components/hypercloud/utils/expandable-table.tsx
- frontend/public/components/hypercloud/utils/help.scss
- kafka mirrormaker2 리스트 화면 > 이중테이블에 tooltip컴포넌트 추가
> [feat][ims 296608] kafka mirrormaker2 리스트 화면 > 이중테이블에 tooltip컴포넌트 추가

- frontend/packages/dev-console/src/utils/hc-status-reducers.ts
hc-status-reducer 파일 lint에러 수정시 생긴 로직 에러 수정 
정상동작
> [feat][patch]IMS 298769 인테그레이션 컨피그 상태값 NO status로 고정되는 오류 수정

- frontend/public/components/nav/perspective-nav.tsx
활성화된 cpm 가 없는 경우 모든 페이지를 렌더링 할수 있도록 수정하였습니다.
> [feat][patch][IMS 299311] 활성화된 cpm 가 없는 경우 모든 페이지를 렌더링 할수 있도록 수정

- frontend/public/components/app.jsx
- frontend/public/components/hypercloud/sas/sas-app.tsx
- frontend/public/components/hypercloud/utils/help.scss
- frontend/public/components/overview/_overview.scss
- frontend/public/components/utils/kebab.tsx
- frontend/public/module/ws-factory.js
- frontend/public/style/_common.scss
> [feat][patch]sas app 페이지 구성

- frontend/public/components/hypercloud/sas/sas-app.tsx
- frontend/public/components/hypercloud/sas/sas-controller.tsx
- frontend/public/components/hypercloud/sas/sas-node.tsx
- frontend/public/components/hypercloud/sas/sas-service.tsx
- frontend/public/components/hypercloud/sas/sas-single-table.tsx
- frontend/public/components/hypercloud/utils/expandable-table.tsx
sas service, node 페이지 테이블 구성, 캐밥 모달 형성
> [feat][patch] sas service, node 페이지 테이블 구성, 캐밥 모달 형성

- frontend/public/components/graphs/area.tsx
- frontend/public/components/graphs/graph-empty.tsx
- frontend/public/style/_overrides.scss
파일시스템 데이터 오류문구 기획 변경으로인한 UI 반영 완료했습니다.
> [feat][patch] pod 상세페이지 파일시스템 데이터 오류 문구 수정

- frontend/public/components/hypercloud/sas/sas-app.tsx
- frontend/public/components/hypercloud/sas/sas-node.tsx
- frontend/public/components/hypercloud/sas/sas-service.tsx
- frontend/public/style/_common.scss
> [feat][patch] sas app modal 6개 ui 및 from 구현

- frontend/public/components/app-contents.tsx
- frontend/public/components/hypercloud/sas/create-sas-app.tsx
- frontend/public/components/hypercloud/sas/create-sas-controller.tsx
- frontend/public/components/hypercloud/sas/sas-app.tsx
- frontend/public/components/hypercloud/sas/sas-controller.tsx
- frontend/public/components/hypercloud/sas/sas-node.tsx
sas app 생성페이지 구현 및 sas 컨트롤러 생성페이지 구현
> [feat][patch]sas app 생성페이지 구현 및 sas 컨트롤러 생성페이지 구현

- frontend/public/components/graphs/area.tsx
- frontend/public/components/graphs/graph-empty.tsx
- frontend/public/components/pod.tsx
pod 상태가 failed 혹은 completed 상태일 경우에 파일 시스템의 "사용 중인 컨테이너 런타임은 해당 항목의 데이터를 제공하지 않음"오류문구를 삭제하고 데이터를 찾을 수 없음으로 오류문구 수정
> [feat][patch]pod 상세페이지 파일시스템 오류문구 수정

- frontend/public/components/hypercloud/kafkamirrormaker2.tsx
- frontend/public/components/hypercloud/sas/create-sas-app.tsx
- frontend/public/components/hypercloud/sas/create-sas-controller.tsx
카프카 미러 메이커 2 커넥터 이름 관련 문구 번역 UI 적용
> [feat][patch][IMS 296608] 카프카 미러 메이커 2 커넥터 이름 관련 문구 번역 UI 적용

- frontend/public/components/app-contents.tsx
- frontend/public/components/hypercloud/sas/create-sas-app.tsx
- frontend/public/components/hypercloud/sas/create-sas-controller.tsx
- frontend/public/components/hypercloud/sas/sas-app.tsx
- frontend/public/components/hypercloud/sas/sas-controller.tsx
- frontend/public/components/hypercloud/sas/sas-node.tsx
- frontend/public/components/hypercloud/sas/sas-service.tsx
- frontend/public/components/hypercloud/sas/sas-single-table.tsx
- frontend/public/components/hypercloud/sas/sas-string.js
sas app 페이지 리팩토링 및 개발자 콘솔 오류 처리 나머지 sas 페이지 refactoring
> [feat][patch] sas app 페이지 리팩토링 및 개발자 콘솔 오류 처리 나머지 sas 페이지 refactoring

- frontend/public/components/hypercloud/sas/sas-app.tsx
- frontend/public/components/hypercloud/sas/sas-single-table.tsx
- frontend/public/components/hypercloud/utils/expandable-table.tsx
> [feat][patch] 테이블 간격 조절 및 필터 내부 숫자 적용

- frontend/public/components/app-contents.tsx
- frontend/public/components/hypercloud/sas/create-cron.tsx
- frontend/public/components/hypercloud/sas/sas-app.tsx
- frontend/public/components/hypercloud/sas/sas-controller.tsx
- frontend/public/components/hypercloud/sas/sas-kebab.tsx
- frontend/public/components/hypercloud/sas/sas-modal.tsx
- frontend/public/components/hypercloud/sas/sas-node.tsx
노드 삭제 모달 구현 컨트롤러 모달 구현 크론생성 페이지 및 링크 구현
> [feat][patch] 노드 삭제 모달 구현 컨트롤러 모달 구현 크론생성 페이지 및 링크 구현

- frontend/public/components/hypercloud/sas/create-cron.tsx
- frontend/public/components/hypercloud/sas/create-sas-app.tsx
- frontend/public/components/hypercloud/sas/create-sas-controller.tsx
- frontend/public/components/hypercloud/sas/sas-app.tsx
- frontend/public/components/hypercloud/sas/sas-controller.tsx
- frontend/public/components/hypercloud/sas/sas-node.tsx
- frontend/public/components/hypercloud/sas/sas-service.tsx
- frontend/public/components/hypercloud/sas/sas-utils.tsx
- frontend/public/style/_common.scss
> [feat][patch] 인라인 css 정리 이전 필터 알고리즘 수정 검색알고리즘 구현 및 검색 구현

- frontend/public/components/factory/table.tsx
- frontend/public/components/hypercloud/factory/table.tsx
- frontend/public/components/ingress.jsx
loadBalancer IP 와 rule 의 path 의 port number 조합을 표기함
> [patch][feat][IMS 290759] Ingress 탭에서 IP, PORT 추가

- frontend/public/components/ingress.jsx
> [feat]주석 삭제

- frontend/public/components/factory/table.tsx
- frontend/public/components/hypercloud/factory/table.tsx
- frontend/public/components/ingress.jsx
[feat][patch][IMS 290759] port 수정
ingress.tls 설정 있으면 80,443 / 없으면 80으로 port 수정
> [feat][patch][IMS 290759] port 수정

- frontend/public/components/ingress.jsx
[feat][patch][IMS 290759] address 표기 host 와 통일
address 표기 host 와 통일
> [feat][patch][IMS 290759] address 표기 host 와 통일

- frontend/public/components/ingress.jsx
hostsStr 값이 없는곳에서 쓰이고 있어서 에러가 나고 있었으므로 수정함
> [bugfix][patch][IMS 290759] Ingress 탭에서 IP, PORT 추가 - hostsStr 제거

- frontend/public/components/ingress.jsx
spec 에 ingres list 가 없는 경우 예외처리
> [patch][bugfix] spec 에 ingres list 가 없는 경우 예외처리

- frontend/public/components/edit-yaml.jsx
- frontend/public/components/hypercloud/crd/create-pinned-resource.tsx
- frontend/public/components/hypercloud/crd/edit-resource.tsx
- frontend/public/components/utils/horizontal-nav.tsx
기본리소스 schema json 을 console 로 내장해서 github api call 이 필요 없어 졌는데도 일부 상황(수정페이지 등)에서 계속 api call 하고 있어서 수정함
> [bugfix][patch][IMS 303093] [5.0] console내 외부 리소스 호출 변경 요청

- frontend/public/components/hypercloud/utils/menu-utils.ts
- frontend/public/hypercloud/menu/hc-default-menus.ts
- frontend/public/hypercloud/menu/menu-types.tsx
[feat][patch][IMS 304498]오픈서치, 깃랩 제거, gitea 추가
- hc-default-menus 에서 OpenSearch 제거
- ingress 조회 key gitlab 에서 gitea 로 수정
- defaultLabel 을 'Gitea' 로 수정(번역 key 요청 필요)
> [feat][patch][IMS 304498]오픈서치, 깃랩 제거, gitea 추가

- frontend/packages/console-excel-to-json/src/index.js
[feat] string v1.25 추가에 따른 script 변경
> [feat] string v1.25 추가에 따른 script 변경

- frontend/public/components/catalog/catalog-items.tsx
> [bugfix] 안 쓰는 import 삭제

- frontend/public/components/hypercloud/utils/menu-utils.ts
- frontend/public/hypercloud/menu/hc-default-menus.ts
- frontend/public/hypercloud/menu/menu-types.tsx
> [feat][patch][IMS 293892]Console에서 Kind: Rollout 조회 제공

- Jenkinsfile
- Jenkinsfile_bak
> [chore]update jenkinsfile

- frontend/public/components/hypercloud/template-instance.tsx
> [feat][patch][IMS 309480] 템플릿 인스턴스 상세 화면에서 서비스 인스턴스 삭제

- frontend/public/components/hypercloud/form/taskruns/create-taskrun.tsx
- frontend/public/components/hypercloud/form/taskruns/sync-form-data.ts
> [bugfix][patch][IMS 309017] 콘솔 ci/cd 메뉴 관련 ui 수정 요청

- frontend/public/hypercloud/menu/hc-default-menus.ts
> [feat][patch] 애플리케이션 메뉴 제거

- frontend/public/components/catalog/catalog-page.tsx
- frontend/public/components/hypercloud/form/taskruns/sync-form-data.ts
- frontend/public/hypercloud/menu/menu-types.tsx
> [feat][patch][IMS 309017][IMS 303122] catalog page에서 return null 하는 부분 임시주석처리, 콘솔 ci/cd 메뉴 관련 ui 수정 요청 Yaml view에apiVersion 추가, 이미지 레지스트리 메뉴명 정상화

- frontend/public/hypercloud/menu/hc-default-menus.ts
> [feat] 마스터 클러스터>관리>파드 보안 정책 메뉴 제거

- Jenkinsfile
> git tag 관련 오류 임시 수정

- Jenkinsfile
> tag 오류 관해서 강제 태깅했던 부분 원복

- frontend/public/hypercloud/menu/hc-default-menus.ts
> [feat][IMS 302150] 싱글 클러스터 > 파드 보안 정책 메뉴 삭제

- frontend/public/components/hypercloud/cluster-registration.tsx
- frontend/public/components/hypercloud/cluster-update-claim.tsx
- frontend/public/components/hypercloud/cluster.tsx
> [bugfix][IMS 293440] 클러스터 업데이트 클레임 탭 삭제

- frontend/public/components/hypercloud/cluster-claim.tsx
[bugfix] 클러스터 클레임 tab에서 클러스터 업데이트 클레임 탭이 나오는 오류 수정
> [bugfix] [IMS 293440]클러스터 클레임 tab에서 클러스터 업데이트 클레임 탭이 나오는 오류 수정

- frontend/public/components/hypercloud/utils/schemas/network/Service.json
sessionAffinityConfig 인풋 안보이는 문제 해결
> [feat] sessionAffinityConfig 인풋 수정

- frontend/public/components/hypercloud/utils/schemas/network/NetworkPolicy.json
Pod Selector 입력 필드에 타입을 추가하여 에러 수정하였습니다.
> [feat] PodSelector 입력 필드 타입 추가

- frontend/public/components/hypercloud/utils/schemas/network/Service.json
> [feat] sessionAffinityConfig schemas 수정

- frontend/packages/dev-console/src/utils/hc-status-reducers.ts
> [feat] 추론 서비스 상태 표시 로직 수정

- frontend/usermanual/4.1-ko/welcome/intro.html
- frontend/usermanual/5-ko/welcome/intro.html
- frontend/usermanual/5.1-ko/welcome/intro.html
- frontend/usermanual/5.1.1-ko/welcome/intro.html
- frontend/usermanual/5.2-ko/welcome/intro.html
> [feat] 메뉴얼 드롭다운 이벤트 수정

- frontend/public/components/hypercloud/form/templateinstances/create-templateinstance.tsx
> [feat] 템플릿 인스턴스 생성시 data 제대로 안넘어가서 error 발생하는 현상

- Jenkinsfile
아직 확실하지 않아서 과거 jenkins 파일 내용은 주석으로 복구함
> [chore] 주석으로 추가
