frontend/public/components/events.jsx
namespace 변경시 바로 적용되도록 함
이벤트 조회 api 에서 null 응답시 이벤트 없음 나오도록 수정
=> [bugfix][patch][IMS]286436 event page bugfix - 네임스페이스 변경 바로 반영, 이벤트 없음 표시 되도록 변경

frontend/packages/console-shared/src/components/dynamic-form/utils.ts, frontend/public/components/hypercloud/crd/create-pinned-resource.tsx, frontend/public/components/hypercloud/crd/edit-resource.tsx, frontend/public/components/hypercloud/crd/index.tsx, frontend/public/components/hypercloud/form/create-form.tsx, frontend/public/components/hypercloud/form/index.ts, frontend/public/components/hypercloud/utils/button-state.tsx
- `dynamic-form/utils.ts` : 특정 필드들에 한해 빈 값이어도 값이 제거되지 않도록 기능 추가
- `생성 공통 폼`(create-pinned-resource.tsx) 및 `수정 공통 폼`(edit-resource.tsx)에 커스텀 폼 prop 추가
- `생성 커스텀 폼`(create-forrm.tsx) : form과 yaml간 데이터 동기화 기능 추가
=> [feat][patch] 커스텀 폼 페이지와 yaml 폼 간 연동 기능 추가

frontend/public/components/hypercloud/form/pipelineresources/create-pipelineresource.tsx, frontend/public/components/hypercloud/form/pipelineresources/sync-form-data.ts, frontend/public/components/hypercloud/pipeline-resource.tsx
Form 뷰에서 레이블이 제대로 작동하지 않는 오류 수정.
Yaml 뷰에서 kind, apiVersion이 누락되었던 오류 수정.
YAML 탭 제거
=> [bugfix] 파이프라인 리소스 - Form 뷰 레이블, Yaml 뷰 apiVersoin 오류 수정

frontend/public/components/configmap-and-secret-data.tsx, frontend/public/components/secrets/create-secret.tsx, scripts/run-console.sh
=> IMS [290316] 시크릿 키/값 시크릿 생성시, 수정시 평문으로 안내 문구 추가 및 시크릿 키/값 상세 보기시 데이터값 표시에 토큰값을 64 인코딩하여 적용

frontend/packages/console-app/src/components/nodes/node-dashboard/queries.ts, frontend/packages/console-shared/src/components/dashboard/utilization-card/UtilizationItem.tsx, frontend/public/components/dashboard/dashboards-page/cluster-dashboard/queries.ts
=> 싱글 클러스터 네트워크 전송 오류 수정을 위한 쿼리 수정 및 알고리즘 수정

frontend/public/components/utils/status-box.tsx
"서비스를 이용하기 위해 사용자 리소스 정의를 생성해 주세요." 를 각각 제목, 상세설명에 넣었습니다.
리스트 정의 생성하기 링크를 누르면 리소스 정의 리스트 페이지가 랜더링 되던 것을 
리소스 정의 생성페이지로 넘어가게 수정했습니다.
crd 화면이 기획문서와 다른것이 발견되어 이를 수정하였습니다.
직접 cr를 만들어 확인하면서 구현을 하였습니다. 
CR을 만들어서 화면을 띄워 보니 빨간 글씨가 쳐저 있는 부분과
리스트 정의 생성하기 링크를 누르면 리소스 정의 생성페이지가 아니라 리소스 정의 리스트 페이지가 랜더링되었습니다. 
이를 수정하여 바꾸었습니다.
=> [feat] crd 화면 기획문서와 다른부분 수정

frontend/public/components/secrets/create-secret.tsx
=> [feat][patch][IMS 1833225] 시크릿 키/값 수정시에도  데이터값 표시에 토큰값을 64 인코딩하여 적용

frontend/public/components/secrets/create-secret.tsx
=> [feat][patch][IMS 290316] 시크릿 키/값 수정시에도  데이터값 표시에 토큰값을 64 인코딩 평문으로 수정

frontend/packages/dev-console/src/components/pipelines/detail-page-tabs/pipeline-details/PipelineVisualizationTask.tsx, frontend/packages/dev-console/src/utils/pipeline-utils.ts, frontend/public/components/hypercloud/helmchart.tsx, frontend/public/components/hypercloud/helmrepository.tsx, frontend/public/components/hypercloud/pipeline-approval.tsx, frontend/public/components/hypercloud/pipeline.tsx
[bugfix][patch][IMS 290754] 파이프라인 승인 user 값 string list 에서 object list 로 변경되어 생긴 문제 수정
파이프라인 승인 user 값 string list 에서 object list 로 변경되어 sting 인지 확인하고 아니면 object 의 name 값으로 나오게 변경함
[bugfix][patch][IMS 290754] 파이프라인 taskRef 가 없는 경우 예외 처리
taskRef 가 없는 경우는 해당 값을 사용하는 부분 넘어가도록 변경함
[bugfix][patch][IMS 294263]헬름 리포지터리 상세페이지 차트 탭 무한로딩 수정
상세페이지의 pages 로 입력한 Page 객체 내부의 component 를 즉시실행 함수로 넣었더니 검색시 무한로딩 되는 현상이 발생
component 를 ChartListPage 로 변경
ChartListPage 위치 변경
=> IMS 290754 파이프라인 taskRef 없을시 예외처리, IMS 294263 헬름리포지터리 상세페이지 내 헬름차트 페이지 무한 로딩 수정

frontend/public/reducers/k8s.ts
created인자를 추가하여 유니크하게 리소스를 추가 할수 있게 하였습니다. 이전에는 하나만 볼수있었던 harbor 를 2개 다 볼수 있게 되었습니다.
=> [feat][patch][IMS 294273] 헬름차트 메뉴에서 이름 중복 리소스 가져오지 않는 현상 수정

frontend/public/components/RBAC/bindings.jsx, frontend/public/components/hypercloud/namespace-claim.tsx, frontend/public/components/hypercloud/resource-quota-claim.tsx, frontend/public/components/hypercloud/role-binding-claim.tsx, frontend/public/components/ingress.jsx, frontend/public/components/namespace.jsx, frontend/public/components/resource-quota.jsx
[feat][patch][IMS 294562] ingress path 의 service port 참조 변경
ingress 의 path 의 service 와 port 위치가 현재 들어오는 응답에 맞추어 변경
[feat][patch][IMS 294562] defaultSelectedRows 사용 안하게 하고 href 수정
defaultSelectedRows 사용시 filter 사용 안함 상태가 생기지 않기 때문에 처음 연결되는 href 만 필터선택된 곳으로 이동하도록 수정
(필터를 지우면 자동으로 기본 필터로 설정함)
=> [feat][patch][IMS 294562] defaultSelectedRows 사용 안하게 하고 href 수정, ingress path 의 service port 참조 변경

frontend/public/components/secrets/create-secret.tsx
생성 : 평문으로 입력하며, 평문 가이드 Text 삭제
상세 : [값 표시하기] 클릭 시, 인코딩된 형태로 제공
수정 : 기존에 입력돼있던 값 Field는 공란으로 제공, 평문 가이드 Text 삭제
+추가) 이때 수정부분에서 키값이 여러개일때 하나의 값만 수정해도 다른 값에 영향 받는 경우가 발생이 되어서 영향 받지 않도록 수정했습니다.
=> [feat][patch][IMS 290316] 콘솔 시크릿 정보 표시 관련 ui 재적용 및 수정시 다른 값이 영향받는 현상 수정

frontend/public/components/hypercloud/search.tsx
=> [feat][patch] IMS 290755 검색 메뉴에 생성 기간 별 조회 기능 시작 날짜 수정

frontend/public/components/namespace-overview.tsx, frontend/public/components/namespace.jsx
What:[IMS 294550] 싱글클러스터 콘솔 잔여 이슈 수정 하였습니다.
Why: 회의 에서 정해진 내용을 토대로 2번 3번 오류를 수정했습니다.
How:
홈 > 네임스페이스
네임스페이스 상세에서 클레임 판넬 이슈
클러스터 템플릿 클레임, 롤바인딩 클레임 링크 각각 클릭시 "404 Not Found" 발생 수정
클레임 판넬 싱글 클러스터에서 삭제
홈 > 네임스페이스
네임스페이스 상세에서 미터링 탭 화면 이슈
싱글 클러스터에서 미터링탭 삭제
=> [feat][patch][IMS 294550] 싱글클러스터 콘솔 잔여 이슈 수정

frontend/public/components/events.jsx
ResourceListDropdown 의 type을 multiple 로 추가하여 여러개 선택시 선택마다 창이 닫히는 과정 없이 연속해서 선택 가능하게 함
=> [bugfix][patch][IMS 290756] [5.0] [천주교] 파드 탭에서 필터 다중 선택 기능 (이슈분리: 290664) - event page 다중 선택시 창 유지

frontend/public/components/dashboard/dashboards-page/cluster-dashboard/details-card.tsx
Version api 에서 Abnormal 정상적으로 보내고 있었으나 코드 오타로 인하여 정상적으로 icon 나오지 않음
=> [bugfix][patch] 개요 페이지 버전 상세 표시 부분 오타 수정

frontend/public/components/resource-dropdown.tsx
what: 싱글 클러스터 검색페이지의 리스트가 
전체 리소스를(마스터 리소스) 띄워주던 것을 
싱글클러스터 리소스만 띄워지게 수정했습니다.
why: 검색 페이지는 싱글 클러스터이던지 마스터 클러스터 이던지 구분하지않고 페이지를 뛰워주는 페이지였습니다. 때문에 전체 리소스를 가공한 함수에서 리덕스를 이용하여 그냥 가져와서 리소스 리스트를 구성하는 방식으로 구동이 되고 있었습니다.
how: 싱글 클러스터의 리소스를 받아온 다음 드롭다운에 맞는 형식으로 가공한다음 랜더링 하도록 하였습니다.
=> [feat][patch][IMS 295182] 싱글 클러스터 검색 리스트 수정

frontend/public/components/resource-dropdown.tsx
[bugfix][IMS]290756 filter 한번에 다중 선택 가능 - checkbox bug 수정
isChecked = true 이면 dropDownItems 내부의 CheckBox component 에서 <input ... checked> 상태로 생성되고 변경사항이 적용되지 않는 문제 발생
checked 로 변경 후 정상동작 확인
https://github.com/tmax-cloud/console/pull/32
와 비슷한 문제
=> [bugfix][patch][IMS 290756] 파드 탭에서 필터 다중 선택 기능 - event page

frontend/packages/console-app/src/components/cloud-shell/hypercloud/HyperCloudShellTerminal.tsx
what: 터미널 pod 생성을 위한 유저 아이디 수정
why: k8s 네이밍 규칙에 맞는 pod를 생성해야하기 때문에 아이디에 _ 를 - 로 수정을 한것에 맞추어 데이터를 받아오는 유저 아이디에서 "_" 를 "-" 로 수정하였습니다.
=> [feat][patch][IMS 291634] k8s 네이밍 규칙에 맞는 pod 생성을 위한 유저 아이디 수정

frontend/packages/console-app/src/components/cloud-shell/cloudShellConfirmationModal.ts, frontend/packages/console-app/src/components/cloud-shell/hypercloud/HyperCloudShellTerminal.tsx, frontend/public/components/modals/confirm-modal.jsx
what: kubectl 커맨창 남은 시간 수정 하였고,  kubect 커맨창 종료시 팝업 제거 하였습니다.
why: getMonth()는 1월이 0부터 시작을 하기때문에 1을 더해주어야 되어서 이를 추가하였습니다. getDate 함수를 사용해야 했던것을 getDay 함수를 사용하여 문제가 발생하여서 이를 수정하였습니다. 이전에 터미널을 닫을때 안내 메세지를 팝업으로 띄워주는 부분이 있었는데 기획상 필요없다는 요청이 들어와서 팝업을 삭제하였습니다.
=> [feat][patch][ims291634] kubectl 커맨창 남은 시간 수정,  kubect 커맨창 종료시 팝업 제거

frontend/public/components/hypercloud/pipeline-approval.tsx
what: 파이프 라인 승인 페이지 상태 필터문구 수정하였습니다.
why:필터문구 기준이 waiting 으로 되어있어서 필터가 안되는 현상이 발생해서 상태와 맞는 필터 문구를 
waiting 에서 Awaiting으로 바꾸어 필터가 정상 작동하도록 하였습니다.
=> [feat] 파이프 라인 승인 페이지 상태 필터문구 수정

frontend/public/components/hypercloud/modals/status-modal.jsx
what:네임스페이스클레임,리소스 쿼타 클레임,클러스터 템플릿클레임 승인처리 팝업 번역 안되는 현상 수정하였습니다.
how: 일반 스트링으로 되어있던 구조를 i18n으로 수정하였습니다.
=> [feat] 네임스페이스클레임,리소스 쿼타 클레임,클러스터 템플릿클레임 승인처리 팝업 번역 안되는 현상 수정

frontend/packages/console-app/src/components/cloud-shell/CloudShellMastheadButton.tsx, frontend/public/components/masthead-toolbar.jsx
what:기획문서를 기준으로 이전에 분리되었던 아이콘 2개를 드랍 다운으로 합쳤습니다.
how: help아이콘을 누르면 터미널창과 이전 메뉴얼창을 들어갈수 있도록 토글을 만들었습니다.
=> [feat][patch] GNB 4a, 4b, 계정관리 항목 아이콘 추가

frontend/public/components/default-resource.jsx
what: crd에 정의 되지 않고 스키마가 없는 리소스의 경우 상세 페이지의 수정탭을 삭제하였습니다.
why: 이전에 스키마도 없고 crd정의도 없는 경우 페이지를 따로 만들어 놓지도 않아서 수정페이지에 들어갈 시 무한 로딩이 되는 현상이 발생하였습니다.
=> [feat][patch] crd에 정의 되지 않고 스키마가 없는 리소스의 경우 상세 - 수정 페이지 삭제

frontend/public/components/hypercloud/exp-timer.jsx
what: 세션만료시간 이후에도 자동 로그아웃되지 않는 현상 수정했습니다.
why: 완료시간이 정확히 60초 남았을때 실행되는 함수가 인지할수있는 시간이 한정적인것으로 추정되어 시간이 넘어가 버려서 실행이 안되는 경우가 있는 것으로 추정됩니다.
=> [feat][patch]세션만료시간 이후에도 자동 로그아웃되지 않는 현상 수정

frontend/public/components/factory/list-page.jsx
해당 프롭스가 없는 경우가 있어서 롤바인딩 페이지가 렌더링 안된던 버그를 수정했습니다.
=> [feat] 롤 바인딩 렌더링 안되는 오류수정

frontend/public/components/edit-yaml.jsx
IMS 내용: sidebar 에 스키마 표시 안되던 문제
원인: spec.validation.openAPIV3Schema 에서만 schema 를 찾은 후 sidebar 에 나오게 하는 문제가 있었음
해결: spec.validation.openAPIV3Schema 가 없을때는 spec.versions[0].schema.openAPIV3Schema 에서 schema 를 확인하도록 수정함
=> [bugfix][patch][IMS 294948][IMS 294952] Redis kafka 국문화 - schema 연결 수정

frontend/public/components/hypercloud/modals/status-modal.jsx
what:서비스콜 보내는 데이터에 한글로 들어가는 오류 수정
why: 승인 번역 하는 과정에서 api 콜을 한글로 보내는 과정이 있어서 이를 수정했습니다.
=> [feat][patch]서비스콜 보내는 데이터에 한글로 들어가는 오류 수정

frontend/public/components/factory/list-page.jsx
what:네임스페이스 변경시에 동기적으로 변하지 않는 props 동기적으로 변하수정 수정
why: 클러스터 -> 클러스터 클레임->모든 네임 스페이스일때 새로고침하고 네임스페이스를 선택하고 생성을 누르면 전 네임스페이스로 들어가는 현상이 발생하였습니다.
props로 전달이 되는 부분에 해당 내용이 useState 로 묶여있어서 Props가 변하는 것을 인지하지 못하는 것이 문제였습니다.
how:useEffect를 추가해서 강제로 인식하도록 바꾸었습니다
=> [feat][patch]네임스페이스 변경시에 동기적으로 변하지 않는 props 동기적으로 변하수정 수정

frontend/public/components/edit-yaml.jsx
schema 에서 properties 가 없으면 sidebar 에서 property 없음 나오는 상황
explore-type-sidebar.tsx
`const currentProperties = _.get(currentDefinition, 'properties') || _.get(currentDefinition, 'items.properties');
...
{_.isEmpty(currentProperties) ? (
<EmptyBox label="Properties" />
) : ( ...`
edit-yaml.jsx 에서 properties 유무 확인 후 definition state 설정함
=> [bugfix] schema 의  properties 없는 경우 sidebar 에 schema 나오지 않게 수정

frontend/public/components/hypercloud/form/helmreleases/create-helmrelease.tsx
what: 헬름 릴리즈 페이지 수정시 오류페이지로 넘어가는 현상 수정하였습니다.
how: 페이지에 없는 인자를 사용하는 코드가 있어서 이를 수정했습니다.
=> [bugfix]헬름 릴리즈 페이지 수정시 오류페이지로 넘어가는 현상 수정

frontend/public/components/hypercloud/form/pipelineruns/create-pipelinerun.tsx, frontend/public/components/hypercloud/form/pipelineruns/sync-form-data.ts, frontend/public/components/hypercloud/form/utils/workspaces.tsx, frontend/public/components/hypercloud/utils/dropdown.tsx
[bugfix] dropdown callback 있을때만 실행하게 함
- dropdown callback 있을때만 실행하게 함
[bugfix] pipelinerun workspace sync-form-data 수정
form 에서 yaml 이동할때 workspaces 변환 되도록 함
추가 개선 필요점
- Volume Claim Template 외는 yaml -> form 돌아올때 값 사라짐
- Volume Claim Template 라디오 버튼 선택시 멈췄다가 나중에 선택될때가 있음
=> [bugfix] dropdown callback 있을때만 실행하게 함, [bugfix] pipelinerun workspace sync-form-data 수정

frontend/public/components/hypercloud/helmchart.tsx
what: 헬름 리포지터리의 이름 클릭시 라우팅되는 기능 구현하였습니다.
=> [feat][patch]헬름 리포지터리의 이름 클릭시 라우팅되는 기능 구현

frontend/public/components/hypercloud/redis-cluster.tsx, scripts/run-console.sh
레디스 클러스터 마스터 컨피그맵, 슬래이브 컨피그맵 없을시 resource아이콘 뜨는 경우 수정하였습니다.
레디스 클러스터 마스터 컨피그맵, 슬래이브 컨피그맵 없을시 사진처럼 아이콘없이 -을 삽입하였습니다.
(사진은 한개만 바꾸어서 설명했지만 실제로는 둘다 수정하였습니다.)
=> [feat][patch] 레디스 클러스터 마스터 컨피그맵, 슬래이브 컨피그맵 없을시 resource아이콘 뜨는 경우 수정

frontend/public/components/hypercloud/form/pipelineruns/create-pipelinerun.tsx, frontend/public/components/hypercloud/form/utils/workspaces.tsx
volumeclaimtemplate을 제외한 pvc, secret, configmap, emptydir의 경우 form view <-> yaml view 타입을 여러번 변경하는 경우 워크스페이스 하위 리소스가 초기화 되는 현상 해결 하였습니다. 
복합적인 여러 원인이 있었습니다.
form view 작성후에 yaml view 로 바꾼다음 form view 으로 돌아올때 
formData는 정상적으로 전달을 받는데 반해서 
useForm의 내부의 데이터가 유실되는 현상이 되었고 
formData는 정상적으로 돌아오기 때문에 
state는 그대로 유지되어 모든 것이 정상작동을 하는것 처럼 보이지만 
form view <-> yaml view 타입을 한번 더 변경을 할때
useForm의 내부의 데이터가 유실되었던 것을 확인하는 
getvalue()작업에서 유실이 확인되어 3번 왔다갔다하는 현상이 발견되었습니다.
이를 해결하기 위해 defaultValue 의 값을 주어 useForm의 내부의 데이터가 유실되는 현상을 막았지만
useCallback의 훅이 사용되었는데 이를 사용하고 전해진 함수에서 사용이 될때 얉은 복사가 되어 props로 전달되지 않았습니다.
useMemo도 useCallback과 마찬가지 문제가 일어났습니다.
이를 수정하여 useEffect 와 useEffect를 사용해 props로 바꾸었지만
9~ 34번정도 form view <-> yaml view의 타입을 변경하면 하위 리소스가 유실되는 경우를 발견하였습니다.
이는 props.persistentVolumeClaim.claimName, …
=> [feat][patch] volumeclaimtemplate을 제외한 pvc, secret, configmap, emptydir의 경우 form view <-> yaml view 타입을 여러번 변경하는 경우 워크스페이스 하위 리소스가 초기화 되는 현상 해결

frontend/public/components/hypercloud/kafkamirrormaker2.tsx
카프카 미러메이커2 화면에서 status값 없어도 에러화면 뜨지 않도록 수정
=> [bugfix][patch]ims296608 status필드없어도 에러발생하지 않도록 수정

frontend/public/components/hypercloud/kafkamirrormaker2.tsx, frontend/public/components/hypercloud/utils/expandable-table.tsx, frontend/public/components/utils/_field-level-help.scss, frontend/public/components/utils/timestamp.tsx
커넥터 이름 help-icon추가 및 카프카 미러메이커2 이중 테이블 구성및 이중테이블 정렬구현하였습니다.
"커넥터 정보가 유효하지 않을 시 해당 값은 불러오기가 불가능한 상태입니다" 문구는 스트링 추가후 수정할 예정입니다.
=> [feat][patch] 커넥터 이름 help-icon추가 및 카프카 미러메이커2 이중 테이블 구성및 이중테이블 정렬구현

frontend/public/components/hypercloud/kafkarebalance.tsx
카프카 클러스터 목표 필드 관련 버그 수정
config.get('hard.goals') -> Object.keys(config).includes('hard.goals')
=> [bugfix][patch]IMS 296608 클러스터 목표 관련 수정

frontend/public/components/hypercloud/kafkarebalance.tsx
kafka rebalnce에서 필요한 kafka cluster를 찾는 방식 변경 
기존: kafka List 를 가져온후 label이  'strimzi.io/cluster:kafka클러스터이름'와 일치하는 객체 찾음.
현재 : kafka get 서비스를 통해 이름으로 검색.
기본방법의 경우 사용자가 리밸런스 객체 생성 후 다시 kafka의 label을 설정해주어야 한다는 번거로움이 있어 수정
=> [patch][feat]kafkarebalance > kafka cluster 객체찾는 방식 변경

frontend/public/components/app-contents.tsx, frontend/public/components/hypercloud/sas/sas-controller.tsx, frontend/public/components/hypercloud/sas/sas-node.tsx, frontend/public/components/hypercloud/sas/sas-service.tsx
=> [feat][patch] 노드 상세 페이지 및 컨트롤러 상세 페이지 구성

frontend/public/components/masthead-toolbar.jsx
[feat][patch][IMS 300246] 상단 메뉴 탭 우측 기준으로 나오게함
id 가 짧아 지면 잘리는 현상 확인
우측에 있는 메뉴인지 옵션으로 지정해줌으로써 문제 해결함
=> [feat][patch][IMS 300246] 상단 메뉴 탭 우측 기준으로 나오게함

frontend/public/components/ingress.jsx
비어있는지 확인하는 것이었으나 판별식에 오류가 있어서 1개 일때도 아무것도 보여주지 않는 문제가 있었음
=> [bugfix][patch] ingress 주소 안나옴 수정

frontend/public/components/edit-yaml.jsx
sample map 에는 key 넣고 edit-yaml.jsx 에서 translate 함수 실행하게 수정
getResourceSidebarSamples 에서는 useTranslation, withTranslation 등이 되지 않아서 key 만 넣고  edit-yaml.jsx 에서 translate 함수 실행하게 수정
번역 key는 추후 추가될 예정
=> [feat] sample map 의 key 를 edit-yaml.jsx 에서 번역되도록 함

frontend/public/components/catalog/catalog-item-icon.tsx, frontend/public/components/catalog/catalog-items.tsx, frontend/public/components/catalog/catalog-page.tsx, frontend/public/components/hypercloud/form/templateinstances/create-templateinstance.tsx
클러스터서비스클래스로 정보를 받아오고 있어 이를 삭제하고 클러스터 템플릿 정보를 불러와 카드뷰 렌더링하도록 수정
=> [feat][patch][IMS-303122] 클러스터 템플릿 정보로 카드뷰 렌더링

frontend/public/co-fetch.js
[feat][patch] tmaxcloud.org 외 다른 도메인에서 credentials include 포함되어야 하므로 임시로 조치함
오승주 연구원 요청
콘솔에서 multicluster라는 subdomain으로 요청을 보내야 하는 경우 현재 
크로스 오리진에 대한 쿠키 처리(credentials: 'include')가 누락 되는 것이 관찰됨
원인
```
const isCallToSubdomain = (url = '') => {
return new RegExp('[a-z]+\\.tmaxcloud\\.org+').test(url) && !url.includes(location.host);
};
```
하드코딩되어 있어 [[tmaxcloud.org](http://tmaxcloud.org/)](http://tmaxcloud.org) 도메인이 아니면 안됨
(오승주 연구원 환경 주소 - [https://console.192.168.109.21.nip.io/](https://console.192.168.109.21.nip.io/))
다른 global domain을 사용해도 credential이 추가가 되도록 요청
조치
tmaxcloud.org RegExp 부분 뺌
다른 문제 발생 등 확인되면 다시 확인할 필요 있음
=> [feat][patch] tmaxcloud.org 외 다른 도메인에서 credentials include 포함되어야 하므로 임시로 조치함
